function init(self)
	msg.post(".", "acquire_input_focus")

	-- state variables
	self.active = true
end

function on_input(self, action_id, action)
	if action_id == hash("touch") or action_id == hash("click") and action.pressed and self.active then
		-- ask GM to spawn level
		local node = gui.get_node("start")
		if gui.pick_node(node, action.x, action.y) then
			msg.post("/gamemanager", "load_level", { level = 1 }) -- [6]
			msg.post(".", "disable")
			self.active = false
		end
	end
end